"""Language packs: everything the pipeline needs to know about a language.

The old pipeline had nine hardcoded structures spread across four files, all of
them German or Norwegian. They are all word lists or small parsers, so they move
into one TOML file per language.

A pack is generated by the LLM the first time a language is used and then
belongs to the human: reviewed, corrected, committed. Nothing consults a model
at runtime, so flags stay deterministic between runs.

Which pack is used where:

  source language   token folding and confidence flags on the transcript
  target language   line-break preferences and negation checks on the output
"""

from __future__ import annotations

import re
import tomllib
import unicodedata
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

from .core import LANG

# A pack that is missing keys still works; these are the fallbacks. An empty
# function-word list simply means every disagreement counts as significant,
# which is noisier but never wrong.
DEFAULTS: dict = {
    "name": "",
    "iso3": "",
    "ner_model": "",
    "transliterate": {},
    "function_words": [],
    "negations": [],
    "break_before": [],
    "never_trail": [],
    "numbers": {"units": {}, "teens": {}, "tens": {}, "scale": {}},
    "elision_suffixes": [],
    "notes": "",
}


@dataclass
class Pack:
    code: str
    name: str = ""
    iso3: str = ""
    ner_model: str = ""
    transliterate: dict[str, str] = field(default_factory=dict)
    function_words: set[str] = field(default_factory=set)
    negations: set[str] = field(default_factory=set)
    break_before: set[str] = field(default_factory=set)
    never_trail: set[str] = field(default_factory=set)
    numbers: dict = field(default_factory=dict)
    elision_suffixes: list[str] = field(default_factory=list)
    notes: str = ""

    # ---------------------------------------------------------------- text
    def norm_token(self, tok: str) -> str:
        """Casefold, strip punctuation, fold the language's own spellings.

        Engines disagree constantly about ß versus ss or ä versus ae. That is a
        formatting difference, not a transcription error, so it is folded away
        before any comparison.
        """
        t = unicodedata.normalize("NFKC", tok).strip().casefold()
        t = re.sub(r"[^\w\s]", "", t, flags=re.UNICODE)
        for a, b in self.transliterate.items():
            t = t.replace(str(a).casefold(), str(b).casefold())
        return t

    def number(self, tok: str) -> int | None:
        """Parse a spelled-out number, or None.

        Handles units, teens, tens, and the joined compounds many languages
        build (German `dreiundzwanzig`, `neunzehnhundertachtunddreissig`).
        Returns None for anything it cannot fully consume, so ordinary words
        pass through untouched.
        """
        if not tok:
            return None
        if tok.isdigit():
            return int(tok)

        units = self.numbers.get("units", {})
        teens = self.numbers.get("teens", {})
        tens = self.numbers.get("tens", {})
        scale = self.numbers.get("scale", {})
        joiner = self.numbers.get("joiner", "und")

        def small(s: str) -> int | None:
            if s in teens:
                return teens[s]
            if s in tens:
                return tens[s]
            if s in units:
                return units[s]
            if joiner and joiner in s:
                a, _, b = s.partition(joiner)
                if a in units and b in tens:
                    return units[a] + tens[b]
            return None

        for word, mult in sorted(scale.items(), key=lambda kv: -kv[1]):
            if word in tok:
                head, _, tail = tok.partition(word)
                h = small(head) if head else 1
                if h is None:
                    return None
                rest = small(tail) if tail else 0
                if rest is None:
                    return None
                return h * mult + rest
        return small(tok)

    def canonical(self, tok: str) -> str:
        """Aggressively normalise a token, for engine comparison only.

        Folds three classes of difference that are formatting or dialect rather
        than transcription error, and which otherwise swamp the confidence
        flags: spelled-out numbers against digits, elided verb and article
        forms, and inflectional endings.

        This deliberately hides some genuine differences. That is the right
        trade for subtitles, where a flagged-everything review doc gets skimmed
        instead of read. Never use it for display or for the transcript itself.
        """
        t = self.norm_token(tok)
        n = self.number(t)
        if n is not None:
            return str(n)
        if self.elision_suffixes:
            suffixes = tuple(self.elision_suffixes)
            while t.endswith(suffixes) and len(t) > 2:
                t = t[:-1]
        return t

    def is_function_word(self, tok: str) -> bool:
        n = self.norm_token(tok)
        return n in self.function_words or self.canonical(tok) in self.function_words

    def is_negation(self, tok: str) -> bool:
        return self.norm_token(tok) in self.negations


def pack_path(code: str) -> Path:
    return LANG / f"{code}.toml"


@lru_cache(maxsize=8)
def load(code: str) -> Pack:
    """Load a language pack, or an empty one if it has not been generated yet.

    Deliberately does not generate on demand: that needs an LLM and would make
    an import have side effects. `steps.langpack_gen` creates missing packs as
    an explicit pipeline step.
    """
    path = pack_path(code)
    data = dict(DEFAULTS)
    if path.exists():
        data.update(tomllib.loads(path.read_text(encoding="utf-8")))

    return Pack(
        code=code,
        name=data.get("name", ""),
        # Falling back to the two-letter code is wrong but visible: an engine
        # rejects it with a clear error rather than silently transcribing the
        # wrong language.
        iso3=data.get("iso3", "") or code,
        ner_model=data.get("ner_model", ""),
        transliterate=dict(data.get("transliterate", {})),
        function_words={w.casefold() for w in data.get("function_words", [])},
        negations={w.casefold() for w in data.get("negations", [])},
        break_before={w.casefold() for w in data.get("break_before", [])},
        never_trail={w.casefold() for w in data.get("never_trail", [])},
        numbers=data.get("numbers", {}),
        elision_suffixes=list(data.get("elision_suffixes", [])),
        notes=data.get("notes", ""),
    )


def exists(code: str) -> bool:
    return pack_path(code).exists()
